name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: "1.0.0"
slug: "smart_hub"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  7777/tcp: 7777
  7780/tcp: 7780
host_network: true
full_access: true
uart: true
image: github.com/dneprojects/SmartHub