---
name: Smart Hub
description: Habitron Smart Hub as Home Assistant Add-on
version: 0.9.8
slug: smart_hub
init: true
arch:
  - aarch64
ports:
  7777/udp: 7777
  7780/tcp: 7780
host_network: true
uart: true
devices: ["dev/serial0"]
full_access: false
devicetree: true
hassio_role: default
"hassio_api": true
"homeassistant_api": true
webui: http://[HOST]:[PORT:7780]/
panel_icon: mdi:power
panel_title: Habitron
