---
name: License Check

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Get explicit and transitive dependencies
      run: |
        pip install -r requirements.txt
        pip freeze > requirements-all.txt
    - name: Check python
      id: license_check_report
      uses: pilosus/action-pip-license-checker@v2
      with:
        requirements: 'requirements-all.txt'
        fail: 'Copyleft'
        exclude: '(?i)^(pylint|aio[-_]*).*'
    - name: Save report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}" > license-report.json
    - name: Upload artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: license-report
        path: license-report.json
    - name: Add to repo
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: './license-report.json'
    
        # Additional arguments for the git commit command. The --message argument is already set by the message input.
        # Default: ''
        commit: --signoff
    
        # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
        # Default: '.'
        cwd: './web'
        default_author: github_actor
        fetch: false
    
        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'Automatic license check'

