---
name: License Check

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check python
      id: license_check_report
      uses: pilosus/action-pip-license-checker@v2
      with:
        requirements: 'requirements.txt'
        fail: 'Copyleft'
        exclude: '(?i)^(pylint|aio[-_]*).*'
    - name: Print report
      if: ${{ always() }}
      run: echo "${{ steps.license_check_report.outputs.report }}"
